name: CD

on:
  release:
    types: ["created"]

jobs:
  cd:
    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
      - name: check version
        run: echo ${{ github.event.release.tag_name }}
      - name: check package.json version
        run: cat package.json | jq -r .version
      - name: stop if package.json version and tag version is different
        run: |
          if [ ${{ github.event.release.tag_name }} != $(cat package.json | jq -r .version) ]; then
            echo "package.json version and tag version is different"
            exit 1
          fi
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
